### ISSUE TITLE
JSR223 tests fail with NPE at getEngine call

### ISSUE THREAD

**Issue by Wasabi375** [Kotlin/kotlin-script-examples#3]
I was trying these examples out because of the discussion here: https://discuss.kotlinlang.org/t/run-user-code-in-the-server/18976?u=wasabi375

I noticed that I can't run the JSR examples. They fail with a NPE during `ScriptEngineManager().getEngineByExtension("main.kts")!!`

I'm guessing that I am missing something during the build setup. Do I have to install anything in addition? I didn't see anything in the readme.

**Comment by ligee** [comment]
Hopefully solved by now, please comment if not.
In general these samples contain gradle build files that describe all dependencies needed to run appropriate examples and tests.
