### ISSUE TITLE
No documentation provided for Repository interface

### ISSUE THREAD

**Issue by anthonydahanne** [Kotlin/kotlin-script-examples#5]
Hello,

I was not able to find any documentation wrt the `Repository` interface.

My current problem is that I can't find a way to provide credentials to a private Nexus registry

I have created a topic in [Kotlin lang Discourse](https://discuss.kotlinlang.org/t/kotlin-script-cant-login-to-private-repository/19688)

Once I discover how to provide credentials to `@Repository`I'll be able to submit a PR with an example.

If anybody can help with that, please let me know!

**Comment by ligee** [comment]
This issue is not about scripting examples. But a PR into the main Kotlin repo would be very welcome.

I can provide some guidance on how to implement it, so if you're interested, let's continue to discuss it in https://youtrack.jetbrains.com/issue/KT-27701
